# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Simplecli < Formula
  desc "A simple CLI tool to explain automated deployments"
  homepage "https://github.com/mnkboy"
  version "1.0.6-beta"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mnkboy/simplecli/releases/download/v1.0.6-beta/simplecli_Darwin_x86_64.tar.gz"
      sha256 "f2f83778ab3460fd2be76a97f1f280ea665b5eb0ad4400c128ce493b44b0ee68"

      define_method(:install) do
        bin.install "simplecli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mnkboy/simplecli/releases/download/v1.0.6-beta/simplecli_Darwin_arm64.tar.gz"
      sha256 "e2681e1a69a892c61595d48264f7c1aeebdb58e4c495dc7167b60519b75910c2"

      define_method(:install) do
        bin.install "simplecli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mnkboy/simplecli/releases/download/v1.0.6-beta/simplecli_Linux_x86_64.tar.gz"
      sha256 "38c3e5d2fa5ee8827ffdb6d82d439d17f693f4dc43dfa113c45ae23cd62e994b"
      define_method(:install) do
        bin.install "simplecli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mnkboy/simplecli/releases/download/v1.0.6-beta/simplecli_Linux_arm64.tar.gz"
      sha256 "50eac88587f87bebc67d23bf630b5c74cf0f6565b03a4b46b8f14834397981c4"
      define_method(:install) do
        bin.install "simplecli"
      end
    end
  end
end
